# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approverId', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('emailId', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('emailId', models.CharField(max_length=100)),
            ],
        ),
    ]
