# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('questionid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('count1', models.IntegerField()),
                ('count2', models.IntegerField()),
                ('count3', models.IntegerField()),
                ('count4', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyname', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Approver',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emailId',
        ),
        migrations.AddField(
            model_name='survey',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.user'),
        ),
        migrations.AddField(
            model_name='question',
            name='surveyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Survey'),
        ),
    ]
