# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20180402_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveymessage',
            field=models.TextField(default='New Survey', max_length=2000),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyname',
            field=models.CharField(max_length=50),
        ),
    ]
