# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20180403_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numberofquestions',
            field=models.IntegerField(default=0),
        ),
    ]
