# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_question_numberofquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default='question', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
