# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180403_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
