# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20180403_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='numberofquestions',
        ),
        migrations.AlterField(
            model_name='survey',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.user'),
        ),
    ]
