# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
