# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_auto_20180407_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='surveyid',
            field=models.IntegerField(),
        ),
    ]
