# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20180407_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='question', max_length=200)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('count1', models.IntegerField()),
                ('count2', models.IntegerField()),
                ('count3', models.IntegerField()),
                ('count4', models.IntegerField()),
                ('surveyid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
