# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20180407_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='surveyid',
        ),
        migrations.AddField(
            model_name='questions',
            name='yid',
            field=models.IntegerField(default=0),
        ),
    ]
