# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20180407_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='count1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='count2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='count3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questions',
            name='count4',
            field=models.IntegerField(default=0),
        ),
    ]
