# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20180407_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questionid',
            field=models.IntegerField(default=0),
        ),
    ]
