# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_questions_questionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='numberofquestions',
        ),
    ]
