# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_remove_survey_numberofquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='approver',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='check1',
            field=models.BooleanField(default=False),
        ),
    ]
