# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_survey_check2'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='check3',
            field=models.BooleanField(default=True),
        ),
    ]
