# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20180414_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='approver',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
