# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_approver_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='numberofdays',
            field=models.CharField(default='18/04/2018', max_length=10),
        ),
    ]
