# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_auto_20180415_0835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='numberofdays',
            new_name='datetillopen',
        ),
    ]
