# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_auto_20180415_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='datetillopen',
        ),
        migrations.AddField(
            model_name='survey',
            name='dateuntilopen',
            field=models.DateField(null=True),
        ),
    ]
